name: flux_timeline
description: A package to help you build highly customisable timelines with Flutter.
version: 2.0.0
repository: https://github.com/devartblake/flux_timeline
homepage: https://github.com/devartblake/flux_timeline
issue_tracker: https://github.com/devartblake/flux_timeline/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

flutter:
